version: '3.8'

services:
  session-server:
    build: .
    image: registry.digitalocean.com/cloudloop/session-server:latest
    deploy:
      replicas: 1
    command: ["python", "redis-check.py", "python", "app.py", "-h", "0.0.0.0", "-p", "5000"]
    ports:
      - "56000:56000"
    depends_on:
      - redis

  uploader:
    image: registry.digitalocean.com/cloudloop/session-server:latest
    deploy:
      replicas: 1
    environment:
      - FLASK_APP=uploader.py
      - FLASK_RUN_PORT=5001
      - FLASK_RUN_HOST=0.0.0.0
      - AIRTABLE_KEY=keyBfwKRUJ6tkf1rX
    command: ["python", "uploader.py"]
    ports:
      - "56001:56001"

  downloader:
    image: registry.digitalocean.com/cloudloop/session-server:latest
    deploy:
      replicas: 1
    environment:
      - FLASK_APP=downloader.py
      - FLASK_RUN_PORT=5002
      - FLASK_RUN_HOST=0.0.0.0
    command: ["python", "downloader.py"]
    ports:
      - "56002:56002"

  loops:
    image: registry.digitalocean.com/cloudloop/session-server:latest
    deploy:
      replicas: 1
    environment:
      - AIRTABLE_KEY=keyBfwKRUJ6tkf1rX
    command: ["python", "loops.py"]
    ports:
      - "56003:56003"

  redis:
    image: registry.digitalocean.com/cloudloop/cloudloop-rejson:latest
    environment:
      - REDIS_PASSWORD #Not yet implemented
    ports:
      - "6379"
    command: redis-server --appendonly yes --loadmodule /usr/lib/redis/modules/rejson.so

volumes:
  redis-data:
