apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    service: redis
spec:
  ports:  
  - name: http
    port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: redis
---
apiVersion: v1
kind: Service
metadata:
  name: session-server
  labels:
    service: session-server
spec:
  ports:  
  - name: http
    port: 56000
    targetPort: 56000
    protocol: TCP
  selector:
    app: session-server
---
apiVersion: v1
kind: Service
metadata:
  name: uploader
  labels:
    service: uploader
spec:
  ports:  
  - name: http
    port: 56001
    targetPort: 56001
    protocol: TCP
  selector:
    app: uploader
---
apiVersion: v1
kind: Service
metadata:
  name: downloader
  labels:
    service: downloader
spec:
  ports:  
  - name: http
    port: 56002
    targetPort: 56002
    protocol: TCP
  selector:
    app: downloader

